#!/bin/bash

#git filter-branch -f --env-filter '
#if [ "$GIT_AUTHOR_NAME" = "Fugang Wang" ];
#then
#    GIT_AUTHOR_NAME="Fugang Wang";
#    GIT_AUTHOR_EMAIL="kevinwangfg@gmail.com";
#fi
#if [ "$GIT_COMMITTER_NAME" = "Fugang Wang" ];
#then
#    GIT_COMMITTER_NAME="Fugang Wang";
#    GIT_COMMITTER_EMAIL="kevinwangfg@gmail.com";
#fi
#' -- --all


git filter-branch -f --commit-filter '
if [ "$GIT_AUTHOR_NAME" = "Fugang Wang" ];
  then 
     export GIT_AUTHOR_NAME="Fugang Wang"; 
     export GIT_AUTHOR_EMAIL="kevinwangfg@gmail.com";
  fi; 
git commit-tree "$@"' -- --all
