#!/bin/bash
# The script moves the github repo from $1/$2 to $3/$4, including all branches and tags
# ref: http://vxtindia.com/blog/how-to-migrate-github-repo-to-another-server-including-all-branches-and-tags/
git clone git@github.com:$1/$2.git
cd $2
git remote add NEWDIR git@github.com:$3/$4.git
git config --add remote.NEWDIR.push '+refs/heads/*:refs/heads/*'
git config --add remote.NERDIR.push '+refs/tags/*:refs/tags/*'
for branch in `git branch -a | grep remotes | grep -v HEAD | grep -v master`; do
    git branch --track ${branch##*/} $branch
done
git push NEWDIR
cd ..
rm -rf $2

# e.g., move futuregrid/teefaa to cloudmesh/teefaa, it executes the following:
#
#git clone git@github.com:/futuregrid/teefaa.git
#cd teefaa/
#git remote add teefaa git@github.com:cloudmesh/teefaa.git
#git config --add remote.teefaa.push '+refs/heads/*:refs/heads/*'
#git config --add remote.teefaa.push '+refs/tags/*:refs/tags/*'
#for branch in `git branch -a | grep remotes | grep -v HEAD | grep -v master`; do     git branch --track ${branch##*/} $branch; done
#git push teefaa
